### ISSUE TITLE
Er Employee 전문분야 및 진료과 

### ISSUE THREAD

**Issue by de-novo** [ho-it-project/api_server#24]
# 이슈
현재  Er Employee 정보에는 (의사, 간호사, 응급구조사)만 존재하고있습니다.
기능 및 디자인은 추가적인 정보를 요구하고 있습니다.

추가적인 정보는 다음과 같습니다.
 
의사 
- 진료과 전문분야

간호사
- 전문분야 

### 김xx (의사) 
- 역할: 전공의 (레지던트)
- 진료과: 응급의학과 
- 전문분야: 없음

### 박xx (의사)
- 역할: 전문의 
- 진료과: 응급의학과
- 전문분야: 중환자의학

# 개선

## ER Employee Role
의사 -> 전공의, 전문의로 분리

## ER Doctor Specialization 테이블 추가
의사의 전문분야 (세부전공) - 현재 세부전공 데이터는 아직 구하지못함

예시 : 중환자 의학, 비뇨정신질환, 접합 ....

## ER Nurse Specialization 테이블 추가

현재 간호사의 전문분야는 13개밖에없지만, 이후 개선 및 추가가 될 수 있기에 테이블 추가

[전문간호사 분야 개선 가능성](https://m.medigatenews.com/news/781734415)
간호사의 전문분야 
- 마취전문
- 보건전문
- 가정전문
- 정신전문
- 감연관리전문
- 노인전문
- 산업전문
- 응급전문
- 중환자전문
- 호스피스전문
- 종양전문
- 아동전문
- 임상전문

**Comment by YJ-AnthonyJo** [comment]
커밋하신 것 확인하였습니다. 🙏
